### ISSUE TITLE
Complete profile page

### ISSUE THREAD

**Issue by BenNewman90** [FACN4/Student-Project-TopCorner#32]
- [ ] Display the current users info from the database. 
- [ ] Enable editing of the info.
- [ ] Create an 'edit'/'save' and a 'create group button.
- [ ] Only include the buttons when a user is on their own profile.
