### ISSUE TITLE
login

### ISSUE THREAD

**Issue by BenNewman90** [FACN4/Student-Project-TopCorner#5]
- [x] html structure (generated in React) #21
- [x] validation with React
- [x] .get to serve the page
- [x] .post to make a query to the database and confirm the user data, then redirect to predictions page with an updated cookie
